version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
